[project]
name = "python-fbas"
version = "0.1.0"
dependencies = [
    "networkx==3.3",
    "platformdirs==4.3.6",
    "py-aiger==6.2.3",
    "py-aiger-cnf==5.0.8",
    "pyapproxmc==4.1.24",
    "pycryptosat==5.11.21",
    "pytest==8.3.3",
    "python-sat==1.8.dev13",
    "requests==2.32.3",
    "z3-solver==4.13.3.0",
    "matplotlib==3.9.2",
    "jupyter==1.1.1"
]

[project.optional-dependencies]
qbf = ["pyqbf @ git+https://gitlab.sai.jku.at/qbf/pyqbf"]

[project.scripts]
python-fbas = "python_fbas.main:main"
python-fbas-deprecated = "python_fbas.deprecated.main:main"
